from recordclass import recordclass

from pyxenoverse.bac.types import BaseType

BACScreenEffect = recordclass('BACScreenEffect', [
    'start_time',
    'duration',
    'u_04',
    'character_type',
    'bpe_effect_id',
    'bone_link',
    'screen_effect_flags',

    'u_10',
    'u_14',
    'u_18',
    'u_1c'
])


# Type 16
class ScreenEffect(BaseType):
    type = 16
    bac_record = BACScreenEffect
    byte_order = 'HHHHIHH Ifff'
    size = 32

    description_type = "bpe_effect_id"
    description = {
        0: 'Brightens up the screen',
        1: 'White Screen',
        2: 'Brightens up the screen',
        3: 'Quick White Flash',
        4: 'Brightness Wavering',
        5: 'Red Tint',
        6: 'Fast Brightness Wavering',
        10: 'Small Motion Blur',
        11: 'Strong Motion Blur',
        12: 'Quick Motion Blur,',
        13: 'Very Small Motion Blur',
        14: 'Light Blue Filter',
        15: 'Quick Motion Blur',
        16: 'Quick Motion Blur',
        17: 'Magenta Filter',
        18: 'Two Different Motion Blurs',
        20: 'Ripple Blur',
        21: 'Ripple Blur',
        22: 'Ripple Blur',
        23: 'Ripple Blur',
        24: 'Gravely Blur',
        25: 'Gravely Blur',
        26: 'Ripple Blur ',
        27: 'Ripple Blur',
        30: 'Solar Flare Screen Effect (Opponent Blind)',
        31: 'blackening around the screen',
        32: 'blackening around the screen',
        33: 'Faint Black Circle',
        34: 'A pair of faint Black Circles',
        35: 'faint Black Circle',
        36: 'Solar Flare Screen Effect (User Activate)',
        37: 'Screen turns completely black',
        40: 'Small Transparent Ring expanding',
        41: 'Transparent Ring',
        42: 'Transparent Ring',
        43: 'Big Transparent Ring',
        44: 'Big Transparent Ring',
        45: 'Big Transparent Ring',
        46: 'Transparent Ring',
        50: 'Brightening of the Screen',
        51: 'Brightening of the Screen',
        52: 'Big Transparent Ring',
        53: 'Blue Tint',
        54: 'blackening around the screen',
        55: 'Screen slightly darkens and desaturates',
        56: 'Screen slightly darkens and desaturates',
        57: 'Screen slightly darkens and desaturates',
        59: "Darken and Desaturate Screen 3 [120]",
        60: 'Screen flashes a faint white',
        61: 'Screen slightly darkens and desaturates',
        63: 'Screen slightly darkens and desaturates',
        64: 'Screen flashes a faint pink for a second',
        65: 'Light Blue Filter Fades in and out',
        66: 'Black Spheres',
        70: 'Standard Black Filter used during Skill Activations',

        # from Xenokit repo
        71: "Quick Blur/Shake [16]",
        72: "Render a Black Void [160]",
        73: "Darken Screen 3 [60]",
        74: "Render a Black Void [200]",
        75: "Flashing Dark-Purple Hue [160]",
        76: "Gradual White Screen Blur 1 [50]",
        77: "Gradual White Screen Blur 2 [80]",
        78: "Invert World Colors [59]",
        79: "Consecutive transparent flashes/shakes [95]",
        80: "Flashing Green Body Outline 1 [30]",
        81: "Red Body Outline [160]",
        82: "Flashing Putple Body Outline [130]",
        83: "Flashing White Body Outline 1 [100]",
        84: "Flashing White Body Outline 2 [100]",
        85: "Flashing White Body Outline 3 [60]",
        86: "Flashing Green Body Outline 2 [30]",
        88: "Flashing Green Body Outline 3 [30]",
        90: "Gradually Darken Background [300]",
        91: "Slightly Fade Out Background [120]",
        92: "Background Flashes Purple [120]",
        93: "Background Flashes Purple, Quick [120]",
        94: "Several Intense Blurs/Shakes [190]",
        95: "Gradualy Fade To White [260]",
        96: "Background Flashes Light-Purple [160]",
        97: "Background Flashes Light-Purple, Slow [190]",
        98: "Quick White Flash [30]",
        100: "Distortion Bulge [199]",
        101: "Intense Zoom Blur [350]",
        110: "Light Blue Haze [190]",
        111: "Light Blue Haze, Intense [140]",
        112: "Light Purple Haze [138]",
        113: "Light Purple Haze, Blur [51]",
        114: "Light Blue Haze, Blur, Intense [130]",
        115: "Warm Light-Blue Hue [186]",
        116: "Light Green Hue [130]",
        117: "Flashing Green Hue [350]",
        118: "Saturated Light Purple Hue [250]",
        119: "Saturated Yellow Hue [130]",
        120: "Darken Background 1 [100]",
        121: "Darken Background 2 [560]",
        122: "Darken Background 3 [560]",
        123: "Black Background [20]",
        124: "Darken Background 4 [30]",
        125: "Light Blue Tint [0]",
        126: "Darken Background 5 [130]",
        127: "Deep Blue Tint [150]",
        128: "Bleached Light Blue Tint [40]",
        129: "Blue Background [30]",
        130: "Fade Background to Blue [352]",
        131: "Fade to Pink Tint [350]",
        132: "Darken Background 6 [60]",
        133: "Background Flashes Light Green [30]",
        140: "Thin Green Body Outline 1 [110]",
        141: "Thin White Body Outline [140]",
        142: "Thin Green Body Outline 2 [400]",
        150: "Very Dark Background [60]",
        151: "Warm Organge Hue 1 [0]",
        152: "Warm Bluish Hue [0]",
        153: "Intense Reddish Hue [0]",
        154: "Slightly Darker Background [60]",
        155: "Gradually Darkens Screen [180]",
        156: "Warm Organge Hue 2 [0]",
        157: "Light Blue Tint [130]",
        158: "Blue Tint [0]",
        159: "Blue Tint, Weaker [0]",
        160: "Blur [500]",
        165: "Various Distortion Effects (Large) [200]",
        170: "Motion Blur/Shakes [90]",
        175: "Gradually Fade Background to Dark Brown 1 [260]",
        176: "Gradually Fade Background to Dark Brown 2 [350]",
        177: "Quick Light Blue Tint Flash [60]",
        178: "Light Blue Tint Flash [150]",
        200: "Distortion Bulge Effects [80]",
        211: "Consecutive Shadowy Flashes, Intense [180]",
        212: "Dark Flash, Blur [19]",
        220: "Single Green Hue Flash 1 [90]",
        221: "Single Dark Green Hue Flash [55]",
        222: "Single Green Hue Flash 2 [65]",
        225: "Vertical Blur [140]",
        226: "Blue Tint Flashes, Shakes [100]",
        227: "Red Tint Flashes, Shakes [160]",
        230: "Gradually Darken Background Slightly [160]",
        231: "Single Pink/Purplish Hue Flash [160]",
        232: "Lighten Background [20]",
        233: "Blurry Shakes [80]",
        234: "Light Blue Hue On Background [160]",
        235: "Purple Hue On Background [140]",
        236: "Intense White Flashes, Shakes [70]",
        237: "Intense White Flash -> Purple Flashes/Shakes [140]",
        240: "Lighten Screen [200]",
        241: "Flash Black Background [50]",
        245: "Red Body Outline [5]",
        246: "Dark Tint, Flashing, Quaking [60]",
        250: "Red Body Outline, Red Background [120]",
        251: "Blue Body Outline, Blue Background [120]",
        252: "Green Body Outline, Green Background [120]",
        253: "Pink Body Outline, Pink Background [120]",
        255: "White Flash [33]",
        256: "White Flash [29]",
        257: "White Body Outline 1 [60]",
        260: "White Body Outline 2 [30]",
        309: "Impact Frame",
    }

    def __init__(self, index):
        super().__init__(index)
